name: Check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Audit dependencies
        run: pnpm audit

      - name: Lint
        run: pnpm check

      - name: Check types
        run: pnpm check:types

      - name: Test
        run: pnpm test --project app --project md --run
